name: Release
on:
  push:
    tags: [ 'v*.*.**' ]
    branches:
      - master
      - adventure4
jobs:
  tag-snapshot:
    uses:  "hboyd2003/github-ci/.github/workflows/tag-snapshot.yml@master"
    with:
      tag-name: "${{ github.ref == 'refs/heads/adventure4' && 'snapshot-adventure4' || 'snapshot' }}"
    permissions:
      contents: "write"
    secrets: "inherit"
  release:
    uses:  "hboyd2003/github-ci/.github/workflows/java-release.yml@master"
    needs: tag-snapshot
    permissions:
      contents: "write"
    with:
      tag_name: "${{ startsWith(github.ref, 'refs/tags/v') && github.ref || (github.ref == 'refs/heads/adventure4' && 'snapshot-adventure4' || 'snapshot') }}"
    secrets: "inherit"
